version: '3.8'

services:
  app:
    image: cp3-imagem
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banco-cp3
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - mysql

  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: banco-cp3
    ports:
      - "3306:3306"
